package Exceptionhandle;

public class ArthmeticException2solution {

	public static void main(String[] args) {
     int x; 
     try {
    	 x=10/0; 
     }catch(Exception e) {
    	 System.out.println("inside the main ");
	}
     
	}

}
