package Exception1;

public class Exceptionex6 {
  public static void main(String[] args) {
	
	  try {
	  System.out.println("in try block");
	  
		  
	  }catch(Exception e) {
		  System.out.println(e);
		  
	  }
	  finally {
		  System.out.println("in finally block");
	  }
}
}
